Exercise 1: 
    Write a Python function which will sum all the following listed items (5,8,2,4,7,9)

In [ ]:

def s():
    global c
    c=0
    for i in range(10):
        calculate=input('Continue adding? Y or N')
        if calculate=='Y':
            a=int(input('Please input number '))
            c=c+a
        else:
            return c

s()

In [ ]:
Exercise 2: Write a Python function whihc will find the product/multiply the items in the following list: (4,3,5,6,2)

In [ ]:
def m():
    global c
    c=1
    for i in range(10):
        calculate=input('Continue multipling? Y or N')
        if calculate=='Y':
            a=int(input('Please input number '))
            c=c*a
        else:
            return c

m()

Given the following array. Using numpy:

In [12]:
import numpy as np

array_hw=np.array([[5,5,8,8,9,8],[7,7,5,3,5,7],[8,7,8,4,2,6],[9,9,7,3,1,4]])
print(array_hw)

#Sort the flattened array
print('The sorted flatten array is:')
print(np.sort(array_hw,axis=None))
print('-----------')

#Sort the second column
print('The sorted along second column array is:')
print(np.sort(array_hw[...,1]))
print('-----------')

#Sort the third row
print('The sorted along third row array is')
print(np.sort(array_hw[2,...]))
print('-----------')

#Extract the second row onwards
print('The second row onwards is:')
print(array_hw[1:,...])
print('-----------')

#Extract the third column onwards
print('The third column onwards is:')
print(array_hw[...,2:])
print('-----------')

#obtain the square of array_hw
print('The square of array_hw is:')
print(np.sqrt(array_hw))
print('-----------')

#Slice the element from the third row and fourth column position 3X4
print('Slice 3X4 is')
print(array_hw[2,3])
print('-----------')

#Obtain the total sum of array_hw
print('Sum of array')
print(array_hw.sum())
print('-----------')

#How many dimentions does array_hw have?
print('Dimention of array')
print(array_hw.ndim)
print('-----------')

#What is the data type listed in array_hw?
print('Datatype of array')
print(array_hw.dtype)
print('-----------')

#What is the size of the memory in bytes consumed by all the elements in array_hw?
print('Bytes of array')
print(array_hw.nbytes)
print('-----------')

[[5 5 8 8 9 8]
 [7 7 5 3 5 7]
 [8 7 8 4 2 6]
 [9 9 7 3 1 4]]
The sorted flatten array is:
[1 2 3 3 4 4 5 5 5 5 6 7 7 7 7 7 8 8 8 8 8 9 9 9]
-----------
The sorted along second column array is:
[5 7 7 9]
-----------
The sorted along third row array is
[2 4 6 7 8 8]
-----------
The second row onwards is:
[[7 7 5 3 5 7]
 [8 7 8 4 2 6]
 [9 9 7 3 1 4]]
-----------
The third column onwards is:
[[8 8 9 8]
 [5 3 5 7]
 [8 4 2 6]
 [7 3 1 4]]
-----------
The square of array_hw is:
[[2.23606798 2.23606798 2.82842712 2.82842712 3.         2.82842712]
 [2.64575131 2.64575131 2.23606798 1.73205081 2.23606798 2.64575131]
 [2.82842712 2.64575131 2.82842712 2.         1.41421356 2.44948974]
 [3.         3.         2.64575131 1.73205081 1.         2.        ]]
-----------
Slice 3X4 is
4
-----------
Sum of array
145
-----------
Dimention of array
2
-----------
Datatype of array
int32
-----------
Bytes of array
96
-----------
